site_name: Open Source Guide
# Repository
repo_name: sktelecom/oss-guide
repo_url: https://github.com/sktelecom/oss-guide
edit_uri: ""
# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: En
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/SK_logo

# Page tree
# Page tree
nav:
  - Home: index.md
  - Use:
    - Installation: getting-started.md
    - Creating your site: creating-your-site.md
    - Publishing your site: publishing-your-site.md
    - Customization: customization.md
    - Troubleshooting: troubleshooting.md
    - Data privacy: data-privacy.md
    - Insiders: insiders.md
    - License: license.md
  - Contribute:
    - Changing the colors: setup/changing-the-colors.md
    - Changing the fonts: setup/changing-the-fonts.md
    - Changing the language: setup/changing-the-language.md
    - Changing the logo and icons: setup/changing-the-logo-and-icons.md
    - Setting up navigation: setup/setting-up-navigation.md
    - Setting up site search: setup/setting-up-site-search.md
    - Setting up site analytics: setup/setting-up-site-analytics.md
    - Adding social links: setup/adding-social-links.md
    - Adding a git repository: setup/adding-a-git-repository.md
    - Adding a comment system: setup/adding-a-comment-system.md
    #- Adding an announcement bar: setup/adding-an-announcement-bar.md
    #- Adding a landing page: setup/adding-a-landing-page.md
  - Open:
    - Admonitions: reference/admonitions.md
    - Buttons: reference/buttons.md
    - Code blocks: reference/code-blocks.md
    - Content tabs: reference/content-tabs.md
    - Data tables: reference/data-tables.md
    - Footnotes: reference/footnotes.md
    - Formatting: reference/formatting.md
    - Icons + Emojis: reference/icons-emojis.md
    - Images: reference/images.md
    - Lists: reference/lists.md
    - MathJax: reference/mathjax.md
    - Meta tags: reference/meta-tags.md
  - Tools:
    - Release notes: changelog.md
    - Upgrading: upgrading.md
    - Deprecations: deprecations.md